In [1]:
import numpy as np
from sklearn import linear_model
import pandas as pd

In [2]:
df = pd.read_csv("home.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [3]:
mbed = int(df.bedrooms.median())
mbed

3

In [4]:
df.bedrooms = df.bedrooms.fillna(mbed)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [5]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [6]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [7]:
reg.predict([[3000,3,15]])

array([615025.])

In [8]:
#exercise

In [9]:
df = pd.read_csv("hiring.csv")
df

experience  test_score  interview_score  salary
0         NaN         8.0                9   50000
1         NaN         8.0                6   45000
2         5.0         6.0                7   60000
3         3.0        10.0               10   65000
4         7.0         9.0                6   70000
5         NaN         7.0               10   62000
6        10.0         NaN                7   72000
7        11.0         7.0                8   80000

In [10]:
df.experience = df.experience.fillna(0)
df.test_score = df.test_score.fillna(int(df.test_score.mean()))
df

experience  test_score  interview_score  salary
0         0.0         8.0                9   50000
1         0.0         8.0                6   45000
2         5.0         6.0                7   60000
3         3.0        10.0               10   65000
4         7.0         9.0                6   70000
5         0.0         7.0               10   62000
6        10.0         7.0                7   72000
7        11.0         7.0                8   80000

In [11]:
reg = linear_model.LinearRegression()
reg.fit(df[["experience","test_score","interview_score"]],df.salary)
reg.coef_

array([2634.90079365,  710.27777778, 2743.96825397])

In [12]:
reg.predict([[12,10,10]])

array([90190.81349206])