In [1]:
import numpy as np

In [2]:
p = np.arange(20,40)
p

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

In [3]:
q = np.random.randint(5,6,8).reshape(2,2,2)
q

array([[[5, 5],
        [5, 5]],

       [[5, 5],
        [5, 5]]])

In [4]:
r = np.random.random(25).reshape(5,5)
r

array([[0.90252602, 0.98095465, 0.93449835, 0.52031104, 0.0589919 ],
       [0.11274424, 0.63285471, 0.39074464, 0.14361338, 0.33755018],
       [0.76696286, 0.47822898, 0.73218636, 0.55567787, 0.2403713 ],
       [0.40974852, 0.61224794, 0.84231211, 0.9303674 , 0.38094645],
       [0.99497817, 0.25134635, 0.89092095, 0.83521235, 0.12095451]])

In [5]:
a = np.random.randint(0,100,20)
a[a%2==0]=-1
a

array([-1, -1, 29, -1, -1, -1, 49, 81, -1, -1,  9, -1, 83, 93, 65, -1, 83,
       -1,  3, -1])

In [6]:
y = r[1:2,:2]
y

array([[0.11274424, 0.63285471]])