In [3]:
import numpy as np

In [4]:
n = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [5]:
n

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [6]:
n.ndim

3

In [7]:
n.shape

(2, 2, 2)

In [8]:
p = np.eye(4,5)

In [9]:
p

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [10]:
np.mean(p)

0.2

In [11]:
np.random.seed(12)
arr = np.random.randint(1,200,(20,3))
arr

array([[ 76, 156, 135],
       [131,   4, 196],
       [ 77, 177,  23],
       [ 50, 181, 134],
       [142, 163, 119],
       [ 75, 129, 118],
       [105,  14,  83],
       [ 90,  36, 191],
       [101, 164, 162],
       [159, 120, 192],
       [ 97, 147, 179],
       [135, 124, 110],
       [ 74, 174, 159],
       [161, 111,  28],
       [188, 188,  80],
       [ 26,  57,   5],
       [197,  66,  45],
       [166, 116,  69],
       [182,  54, 108],
       [176,  61, 171]])

In [12]:
np.random.seed(34)
arr = np.random.randint(1,100,9)

In [13]:
arr

array([34, 86, 69, 36, 70, 12, 79, 30, 19])

In [14]:
np.random.shuffle(arr)
arr

array([36, 69, 34, 86, 70, 30, 79, 12, 19])

In [15]:
np.unique(arr)

array([12, 19, 30, 34, 36, 69, 70, 79, 86])

In [16]:
np.random.seed(5)
r = np.random.randint(1,10,9).reshape(3,3)
r

array([[4, 7, 7],
       [1, 9, 5],
       [8, 1, 1]])

In [17]:
np.unique(r,return_index=True,return_counts=True)

(array([1, 4, 5, 7, 8, 9]),
 array([3, 0, 5, 1, 6, 4], dtype=int32),
 array([3, 1, 1, 2, 1, 1]))

In [18]:
r

array([[4, 7, 7],
       [1, 9, 5],
       [8, 1, 1]])

In [19]:
q = arr.reshape(3,3)
q

array([[36, 69, 34],
       [86, 70, 30],
       [79, 12, 19]])

In [20]:
np.vstack((q,r))

array([[36, 69, 34],
       [86, 70, 30],
       [79, 12, 19],
       [ 4,  7,  7],
       [ 1,  9,  5],
       [ 8,  1,  1]])

In [21]:
q

array([[36, 69, 34],
       [86, 70, 30],
       [79, 12, 19]])

In [23]:
q[0:2,1]

array([69, 70])